# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 10.168.26.20/library/recon-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "staging"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

volumeMounts:
  - name: recon-api-secret-volume
    mountPath: /etc/recon-api-secret-volume
  - name: recon-api-xls-data
    mountPath: /usr/recon-api/storage/app/export

env:
  - name: DB_PASSWORD_RACON_AUTH
    valueFrom:
      secretKeyRef:
        name: recon-api-secret
        key: DB_AUTH_PASSWORD
  - name: DB_PASSWORD_SERVER_RECON
    valueFrom:
      secretKeyRef:
        name: recon-api-secret
        key: DB_RECON_PASSWORD
  - name: DB_PASSWORD_SERVER_REPORT
    valueFrom:
      secretKeyRef:
        name: recon-api-secret
        key: DB_REPORT_PASSWORD

volumes:
  - name: recon-api-secret-volume
    secret:
      secretName: recon-api-secret
  - name: recon-api-xls-data
    persistentVolumeClaim:
      claimName: recon-api-xls-vol

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

istio:
  enabled: true
  gateway:
    name: "k3s-gateway"
    port:
      number: 80
      name: http
      protocol: HTTP
      hosts:
        - "*"
  virtualservice:
    port:
      number: 8000
      prefix: /api
      hosts:
        - "*"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []