{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: {{ .Values.istio.gateway.port.number }}
        name: {{ .Values.istio.gateway.port.name  }}
        protocol: {{ .Values.istio.gateway.port.protocol }}
      hosts:
        {{- range .Values.istio.gateway.port.hosts }}
        - {{ . | quote }}
        {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}-vs
spec:
  hosts:
    {{- range .Values.istio.virtualservice.port.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ .Values.istio.gateway.name }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.istio.virtualservice.port.prefix }}
      route:
        - destination:
            host: {{ include "chart.fullname" . }}
            port:
              number: {{ .Values.istio.virtualservice.port.number }}
{{- end }}
